=== d0nn13/MASHUG/media/dtd/hiscores.dtd
<!ELEMENT hiscores (game, game, game)>
<!ELEMENT game (entry+)>
<!ATTLIST game name (spaceinvaders|galaga|rtype) #REQUIRED>
<!ELEMENT entry EMPTY>
<!ATTLIST entry nickname CDATA #REQUIRED>
<!ATTLIST entry score CDATA #REQUIRED>
<!ATTLIST entry date CDATA #REQUIRED>

=== d0nn13/MASHUG/media/hiscores.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE hiscores SYSTEM "dtd/hiscores.dtd">
<hiscores>
  <game name="spaceinvaders">
    <entry nickname="manu" score="3000"/>
    <entry nickname="donnie" score="2000"/>
    <entry nickname="ibrah" score="1000"/>
    <entry nickname="donnie" score="500"/>
    <entry nickname="ibrah" score="400"/>
    <entry nickname="manu" score="300"/>
    <entry nickname="donnie" score="200"/>
    <entry nickname="ibrah" score="100"/>
    <entry nickname="donnie" score="50"/>
    <entry nickname="hitch" score="42"/>
  </game>
  <game name="galaga">
    <entry nickname="nbat" score="3000"/>
    <entry nickname="manu" score="1000"/>
    <entry nickname="donnie" score="500"/>
  </game>
  <game name="rtype">
    <entry nickname="ibrah" score="3000"/>
    <entry nickname="nbat" score="1000"/>
    <entry nickname="manu" score="500"/>
  </game>
</hiscores>
